# Docs Descriptor Format of Catalog Entities:
#   https://backstage.io/docs/features/software-catalog/descriptor-format

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-fpaas-php-web-wordpress
  description: WordPress Demo
  tags:
    - php
    - orangedemos
  system: default
  links:
    - url: https://wordpress.org/
      title: WordPress Homepage
      icon: docs
    - url: https://cloud.orange-business.com/
      title: Orange Cloud for Business
      icon: catalog
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=demo-fpaas-php-web-wordpress'
spec:
  type: website
  lifecycle: production
  owner: odemo-team-alpha
  system: odemo-orange
  dependsOn:
    - component:mariadb
